language: c

addons:
  apt:
    packages:
      - pmake
      - splint

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bsdmake; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pmake LINT=splint; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bsdmake; fi
